version: '3'
services:

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - jgim_bridge
    restart: always
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - www_data:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - jgim_bridge
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - www_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - jgim_bridge
    ports:
      - "443:443"
    env_file:
      - .env

volumes:
  db_data:
    name: db_data
    driver_opts:
      type: none
      device: /home/jgim/data/db_data
      o: bind

  www_data:
    name: www_data
    driver_opts:
      type: none
      device: /home/jgim/data/www_data
      o: bind

networks:
  jgim_bridge:
    driver: bridge

