version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - www-data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    volumes:
      - www-data:/var/www/wordpress
    ports:
      - 443:443
    env_file:
      - .env

volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/jgim/data/db-data
      o: bind
  www-data:
    driver_opts:
      type: none
      device: /home/jgim/data/www-data
      o: bind

networks:
  inception:
    driver: bridge
